spring:
  datasource:
    url: jdbc:mysql://localhost:3306/items?useSSL=false
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: update
      show-sql: false
      format_sql: true
    database: mysql

  debug: true




